#!/bin/bash
set -euo pipefail

source "$(dirname "$0")/version"

cd "$(dirname "$0")/.."

declare -A OS_ARCH_ARG

OS_PLATFORM_ARG=(linux windows)
OS_ARCH_ARG[linux]="amd64"
OS_ARCH_ARG[windows]="amd64"

if [ -z "${CROSS:-}" ]; then
    OS_PLATFORM_ARG=(linux)
fi

rm -rf bin/*
mkdir -p bin
for OS in "${OS_PLATFORM_ARG[@]}"; do
    for ARCH in ${OS_ARCH_ARG[${OS}]}; do
        OUTPUT_BIN="bin/$OS/$ARCH/per-host-subnet"
        if [ "$OS" = "windows" ]; then
            OUTPUT_BIN="${OUTPUT_BIN}.exe"
        fi
        echo "Building per-host-subnet ${VERSION} for ${OS}/${ARCH}"
        GOARCH=$ARCH GOOS=$OS CGO_ENABLED=0 go build \
            -trimpath -buildvcs=false \
            -ldflags="-buildid= -X main.buildVersion=$VERSION -s -w" \
            -o "${OUTPUT_BIN}" ./
    done
done
