#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo Running tests

PACKAGES=$(go list ./... | grep -Ev '(/vendor/)' || true)

[ "${ARCH:-}" == "amd64" ] && RACE=-race
go test ${RACE:-} -covermode=atomic ${PACKAGES}
